name: 'GitHub DataCite'
description: 'Extract DataCite xml-file from GitHub'
inputs:
  repoOwner:
    description: "The owner of the repository"
    required: true
  repoName:
    description: "The name of the repository"
    required: true
  apiToken:
    description: "The API token to access GitHubs APIs"
    required: true
  githubUrl:
    description: "The URL to the GitHub instance"
    default: "https://github.com"
  githubApiUrl:
    description: "Url to the GitHub API."
    default: "https://api.github.com"
outputs:
  datacitexml:
    description: 'The DataCite XML file'
runs:
  using: 'docker'
  image: 'Dockerfile'
