name: 'GitHub DataCite'
description: 'Extract DataCite xml-file from GitHub'
inputs:
  repoOwner:
    description: "The owner of the repository"
    required: true
  repoName:
    description: "The name of the repository"
    required: true
  apiToken:
    description: "The API token to access GitHubs APIs"
    required: true
outputs:
  dataCiteXML:
    description: 'The DataCite XML file'
runs:
  using: 'docker'
  image: 'Dockerfile'
