services:
  backend:
    build: ./github_cite
    ports:
     - "8081:80"
  
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend
    environment:
      API_URL: http://localhost:8081